bossbars:
  first:
    title: '&bThe first bossbar'
    color: 'BLUE'
    style: 'SOLID'
    delay: '10.0'
  second:
    title: '&aThe second bossbar'
    color: 'GREEN'
    style: 'SEGMENTED_6'
    delay: '10.0'
    steps: '1.0' # NEVER SET THE VALUE TO 0!
  third:
    title: '&dThe third bossbar'
    color: 'PINK'
    style: 'SEGMENTED_10'
    delay: '10.0'
    steps: '100.0'
  fourth:
    title: '&5The fourth bossbar'
    color: 'PURPLE'
    style: 'SEGMENTED_12'
    delay: '10.0'
    steps: '-10.0'
  fifth:
    title: '&cThe fifth bossbar'
    color: 'RED'
    style: 'SEGMENTED_20'
    delay: '10.0'
    steps: '-100.0'
