name: xBossBar
version: '${project.version}'
main: space.xbossbar.BossBarPlugin
api-version: '1.16'
author: xentany
commands:
  xbossbar:
    permission: xbossbar.use
permissions:
  xbossbar.use:
    default: op
